---
- hosts: all
  #user: root
  become: yes
  gather_facts: yes
  connection: ssh
  vars:
    workdir: /var/www/html/
  tasks:
    - name: installation apache2
      apt: pkg=apache2 state=present

    - name: version check
      apt: pkg=apache2 state=latest
    - name: clone the git directory
      ansible.builtin.command: git clone https://github.com/GudditiNaganjaneyulu/MyResume.git
    - name: copy files to workdir
      copy: src=/root/ansible/MyResume/  dest='{{workdir}}'
    - name: remove Html code after copying
      ansible.builtin.command: rm -rf /root/ansible/MyResume/

    - name: service starting
      service: name=apache2 state=restarted
